fix: blocks with a lot of requests
iotaledger/wasp-dashboard pull request #514
Opened 2023-05-16 08:22 UTC by evavirseda

# Description of change

1. show spinner while a block is still loading
2. add carousel to display block requests

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

open a `block explorer page` of a block with a lot of requests, try to refresh the page

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code

2023-05-16 08:51 UTC, begonaalvarezd requested changes
Very nice 🚀 
I would add information about the total slides in the carousel and also double arrows to go to first and last 🙏🏼

2023-05-16 09:05 UTC, marc2332 approved these changes

2023-05-17 10:18 UTC, begonaalvarezd requested changes
Looking very good, some final commets:

- There is a not found flash
- The navigation tabs should not disappear while the block loads

![image](https://github.com/iotaledger/wasp-dashboard/assets/3624944/bfd3eb4a-1cf3-42a7-8d0e-61051db5b387)
![image](https://github.com/iotaledger/wasp-dashboard/assets/3624944/654299e3-e2de-443d-a9b0-d8fa2561c649)

2023-05-17 13:17 UTC, begonaalvarezd approved these changes
🚀 amazing work

2023-05-17 13:18 UTC, merged