feat: limit number of cached blocks to 100
iotaledger/wasp-dashboard pull request #524
Opened 2023-05-18 07:26 UTC by evavirseda

# Description of change

Closes #320 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code

2023-05-18 09:44 UTC, begonaalvarezd requested changes

2023-05-18 09:44 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +    private _cachedBlocksOfChain: Record<string, ChainCachedData>;
I wouldnt duplicate this, we can use `_cachedChains`

2023-05-18 09:44 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +        this._cachedBlocksOfChain = this._storageService.load("chain with blocks") ?? {};
I wouldnt update this, just replace it with the new format

2023-05-18 09:44 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +    private saveCachedBlocks() {
we can keep this called `save` as before

2023-05-18 09:44 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +    private cacheBlocksChain(chainID: string, blockIndex: number, block: BlockData) {
We can rename this as you are caching only 1 block extra, and blockIndex shouldnt be necessary as you already have it in `block`
```suggestion
    private cacheChainBlock(chainID: string, block: BlockData) {
```

2023-05-18 09:44 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +        if (this.cacheBlocksChain !== undefined) {
I would generate a migration manager in the project to manage any necessary migration, versioning whats stored in the localStorage

2023-05-23 16:52 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +        this.cacheBlockChain(chainID, block);
```suggestion
        this.cacheChainBlock(chainID, block);
```
🙈

2023-05-23 17:16 UTC, begonaalvarezd requested changes
really good work 🙏🏼 added some comments

2023-05-23 17:16 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +        this.cacheBlockChain(chainID, block);
```suggestion
        this.cacheChainBlock(chainID, block);
```

2023-05-23 17:16 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +        const MAX_CACHED_BLOCKS = 20;
we havwe this const created in multuple places, here is 20 and somewhere else is 100

2023-05-23 17:16 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +            this._cachedChains[chainID].blocks.shift();
why do we need this `shift` here plus a slice right below? would it be enough with slice?

2023-05-23 17:16 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +        this._cachedChains[chainID].blocks = this._cachedChains[chainID].blocks
Also, wouldnt this code potentially cache the same block N times? We are lacking a check that the block doesnt exist already

2023-05-23 17:16 UTC, begonaalvarezd commented on src/lib/classes/services/chainsService.ts
> +        this._cachedChains[chainID].blocks = this._cachedChains[chainID].blocks
Indeed its caching the same block N times 
![image](https://github.com/iotaledger/wasp-dashboard/assets/3624944/a692c02f-b612-45c7-91eb-c4d83ee7d37a)

2023-05-23 17:16 UTC, begonaalvarezd commented on src/lib/classes/services/localStorageService.ts
> +                if (key !== "persisted data version" && json === null) {
why do we run the migration if the key is not this one? We cant make sure the entire local storage is loaded at this point I think

2023-05-23 17:16 UTC, begonaalvarezd commented on src/lib/migration/chainCache.ts
> +    const version = storageService.load("persisted data version") ?? 1; // Get the current version
we have too many conventions in the local storage key name, lets unify them all 🙏🏼 
![image](https://github.com/iotaledger/wasp-dashboard/assets/3624944/318bb61c-0bc4-44a3-884d-e1fdf583ed41)
 I think `this-that` works fine

2023-05-23 17:16 UTC, begonaalvarezd commented on src/lib/migration/chainCache.ts
> +    const version = storageService.load("persisted data version") ?? 1; // Get the current version
Also we should avoid magic strinngs eg `persisted data version`

2023-05-23 17:16 UTC, begonaalvarezd commented on src/lib/migration/chainCache.ts
> +        migratePersistedChains(version + 1);
I would make this agnostic and keep a map of verison numbers and migrations from vx to vx+1, just like here https://github.com/iotaledger/firefly/blob/develop/packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts#L42. With the code you have now you are forcing every single migration to be the exact same function and logic, just the version that is set at the end changes, but all migrations will do the same

2023-05-26 08:18 UTC, marc2332 requested changes

2023-05-26 08:18 UTC, marc2332 commented on src/lib/utils/migration.ts
> +        const blocks = [...chains[chainID].blocks].filter(block => block !== undefined && block !== null);
This can be simplified to:
```suggestion
        const blocks = [...chains[chainID].blocks].filter(Boolean);
```

2023-05-26 08:18 UTC, marc2332 commented on src/lib/classes/services/chainsService.ts
> +            cachedChainBlocks = cachedChainBlocks.filter(b => b !== undefined && b !== null);
Same
```suggestion
            cachedChainBlocks = cachedChainBlocks.filter(Boolean);
```

2023-05-26 08:18 UTC, marc2332 commented on src/lib/utils/migration.ts
> +];
Similar design to firefly:

```suggestion

type Migration = () => void;

const MIGRATIONS: Record<number, Migration> = {
    1: migrateToVersion2
};
```

2023-05-26 08:18 UTC, marc2332 commented on src/lib/utils/migration.ts
> +        MIGRATIONS.find(migration => migration.version === version)?.migrateFunction();
```suggestion
        MIGRATIONS[version]?();
```

2023-05-26 08:48 UTC, marc2332 approved these changes

2023-05-26 09:13 UTC, begonaalvarezd requested changes
almost ready 🙌🏼

2023-05-26 09:13 UTC, begonaalvarezd commented on src/lib/enums/general.enums.ts
> +    ShowHexAsText = "show-hex-as-text",
this key has a new name, we should apply a migration to it 🙏🏼 currently its getting duplicated, users might get the old data + the new data

2023-05-26 09:44 UTC, begonaalvarezd requested changes
Im getting this error because from what its on develop it seems like i have "undefined" so the migration crashes, we should try to manage all edge cases
![image](https://github.com/iotaledger/wasp-dashboard/assets/3624944/236417e7-c449-4fcc-9852-eebd72aad038)

2023-05-26 09:44 UTC, begonaalvarezd commented on src/lib/utils/migration.ts
> +    storageService.save(LocalStorageKey.Chains, chains);
lets move this line a bit above so chains are with chains and showastext are all togteher

2023-05-29 11:14 UTC, begonaalvarezd requested changes

2023-05-29 11:14 UTC, begonaalvarezd commented on src/lib/utils/migration.ts
> +            storageService.remove(LocalStorageKey.Chains);
I dont think it makes sense to have this code here, that actually runs on every migration. This should be added to  `migrateToVersion2` as a catch of each relevant section. Also, `showHexAsText` potentially will not be removed so it needs to be taken into account in the catch 🙏🏼

2023-05-29 14:05 UTC, begonaalvarezd approved these changes

2023-05-29 14:05 UTC, merged